### ISSUE TITLE
What data fields does WI import from PopIt - if others imported, can they be displayed?

### ISSUE THREAD

**Issue by paullenz** [ciudadanointeligente/write-it#912] opened 2015-04-13 19:05 UTC
Playing I added in an area represented by the people and reimported the data to see if this this would be displayed anywhere - it wasn't.  So from this:

- Are there any other data fields imported other than name and email address?
- Can these - e.g. party, org, area represented be shown (in the first instance, something as simple as area represented in brackets after the name)?

**Comment by paullenz** [comment] 2015-04-13 19:08
Sorry - I should totally have said - this is not something needed for this week, but longer term useful

**Comment by tmtmtmtm** [comment] 2015-04-13 19:09
We've had numerous discussions about this, and though it *seems* like this should be easy, it's actually pretty difficult to do in a generic way, based on the way PopIt/Popolo works right now.

EveryPolitician is currently dealing with exactly the same issue, and lots of the discussions on the Poplus list about the spec and how to model things will make this a lot easier. So it's definitely in the plan for ASAP, but not for this week!

**Comment by tmtmtmtm** [comment] 2015-04-14 10:16
Closing as duplicate of #821

**Closed by tmtmtmtm** 2015-04-14 10:16 UTC
Labels: duplicate
