### ISSUE TITLE
Change the address and domain messages are sent from

### ISSUE THREAD

**Issue by henare** [ciudadanointeligente/write-it#1134] opened 2016-02-23 05:06 UTC
To be able to use the hosted version of WriteIt I need to be able to change the email address and domain that messages are sent from. Getting emails from @writeit.ciudadanointeligente.org would be a bit strange.

I can't see how to do this right now.

**Comment by tmtmtmtm** [comment] 2016-02-23 07:27
Dupe of https://github.com/ciudadanointeligente/write-it/issues/374

**Closed by tmtmtmtm** 2016-02-23 07:27 UTC
